OrdiniSDG/Controllers/ArticlesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OrdiniSDG.Classes.EF;
using Newtonsoft.Json;
using Microsoft.AspNet.Identity;

namespace OrdiniSDG.Controllers
{
    public class ArticlesController : BaseController
    {
        // GET: Articles
        public ActionResult Index()
        {
            return View();
        }
        [Authorize]
        public JsonResult ReadArtCGross(string filter = null)
        {
            return Json(ListinoComputerGross.searchItem(filter), JsonRequestBehavior.AllowGet);
        }
        [Authorize]
        public JsonResult ReadArtSap(string filter = null)
        {
            return Json(SAP_Articoli.searchItem(filter), JsonRequestBehavior.AllowGet);
        }

        //Leggo classi articoli da SAP
        
        public JsonResult ReadAreas(string filter = null)
        {
            return Json(SAP_AREA_AFFARI.getList(filter), JsonRequestBehavior.AllowGet);
        }
        
        public JsonResult ReadClasses(string filter = null)
        {
            return Json(SAP_CLASSEV.getList(filter), JsonRequestBehavior.AllowGet);
        }
        public JsonResult ReadSectors(string filter = null)
        {
            return Json(SAP_SETTORE.getList(filter), JsonRequestBehavior.AllowGet);
        }

    }
}

OrdiniSDG/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Collections;
using System.Linq;
using System.Web;
using System.Reflection;
using System.Web.Mvc;
using OrdiniSDG.Classes.EF;
using Newtonsoft.Json;
using Microsoft.AspNet.Identity;

namespace OrdiniSDG.Controllers
{
    public class CustomerController : BaseController
    {
        // GET: Customer
        public ActionResult Index()
        {
            return View();
        }

        [Authorize]
        public JsonResult Read(string filter=null)
        {
            return Json(SAP_Clienti.getList(filter), JsonRequestBehavior.AllowGet);
        }

        public JsonResult ReadAddresses(string codCli, string filter=null)
        {
            return Json(SAP_Destinazioni.getList(codCli,filter), JsonRequestBehavior.AllowGet);
        }
        public JsonResult ReadPayMeth()
        {
            return Json(SAP_Modalita_Pagamento.getList(), JsonRequestBehavior.AllowGet);
        }
        public JsonResult ReadPayCond(string filter = null)
        {
            return Json(SAP_Condizione_Pagamento.getList(filter), JsonRequestBehavior.AllowGet);
        }
    }
}

OrdiniSDG/Controllers/KitHeadController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OrdiniSDG.Classes.EF;
using Newtonsoft.Json;
using Microsoft.AspNet.Identity;

namespace OrdiniSDG.Controllers
{
    public class KitHeadController : BaseController
    {
        // GET: KitHead
        [Authorize]
        public ActionResult Index()
        {
            return View();
        }

        [Authorize]
        public ContentResult ReadAll()
        {
            //Leggo dalla vista per avere il prezzo totale sempre aggiornato
            return Content(JsonConvert.SerializeObject(vw_KitHead.getKitHead( int.Parse(User.Identity.GetUserId())),
                Formatting.None, new JsonSerializerSettings() { ReferenceLoopHandling = Newtonsoft.Json.ReferenceLoopHandling.Ignore }),
                "application/json");
        }

        //public JsonResult Read(int skip, int take)
        //{
        //    return Json(KIH_KitHead.getPartialList(skip, take), JsonRequestBehavior.AllowGet);
        //}

        public ContentResult Update(string model)
        {
            return Content(JsonConvert.SerializeObject(KIH_KitHead.update(JsonConvert.DeserializeObject<KIH_KitHead>(model), int.Parse(User.Identity.GetUserId())),
                Formatting.None, new JsonSerializerSettings() { ReferenceLoopHandling = Newtonsoft.Json.ReferenceLoopHandling.Ignore }),
                "application/json");
        }
        public ContentResult Destroy(string model)
        {
            return Content(JsonConvert.SerializeObject(KIH_KitHead.delete(JsonConvert.DeserializeObject<KIH_KitHead>(model), int.Parse(User.Identity.GetUserId())),
                Formatting.None, new JsonSerializerSettings() { ReferenceLoopHandling = Newtonsoft.Json.ReferenceLoopHandling.Ignore }),
                "application/json");

        }
        public ContentResult Create(string model)
        {
            return Content(JsonConvert.SerializeObject(KIH_KitHead.create(JsonConvert.DeserializeObject<KIH_KitHead>(model), int.Parse(User.Identity.GetUserId())),
                Formatting.None, new JsonSerializerSettings() { ReferenceLoopHandling = Newtonsoft.Json.ReferenceLoopHandling.Ignore }),
                "application/json");

        }
    }
}

OrdiniSDG/Views/Shared/_FooterPartial.cshtml
<!-- Footer -->
<footer class="clearfix">
    <div class="pull-right">
        Crafted by <a href="http://www.lyb.it" target="_blank">Lyb</a>
    </div>
    <div class="pull-left">
        <span id="year-copy"></span> &copy; <a href="http://www.lyb.it" target="_blank">ORDINI SDG 0.1</a>
    </div>
</footer>
<!-- END Footer -->

OrdiniSDG/Views/Shared/_SidebarNavigationPartial.cshtml
@using Microsoft.AspNet.Identity
@if (Request.IsAuthenticated)
{
    <script>

        $(document).ready(function (){
            $("#hMenu"+"@ViewBag.Title").addClass("active");
        })

    </script>
    <!-- Sidebar Navigation -->
<ul class="sidebar-nav">
    @*<li>
            <a href="@Url.Action("Index","Home")" ><i class="gi gi-stopwatch sidebar-nav-icon"></i><span class="sidebar-nav-mini-hide">Dashboard</span></a>
        </li>*@

    <li class="sidebar-header">
        @* <span class="sidebar-header-options clearfix"><a href="javascript:void(0)" data-toggle="tooltip" title="Quick Settings"><i class="gi gi-settings"></i></a><a href="javascript:void(0)" data-toggle="tooltip" title="Create the most amazing pages with the widget kit!"><i class="gi gi-lightbulb"></i></a></span>*@
        <span class="sidebar-header-title">GESTIONE</span>
    </li>
    <li>
        <a class="@(ViewContext.RouteData.Values["Action"].ToString() == "OrderHead" ? "active" : "")" id="hMenuOrdini" href="@Url.Action("Index","OrderHead")"><i class="gi gi-charts sidebar-nav-icon"></i><span class="sidebar-nav-mini-hide">Ordini</span></a>
    </li>
    @if (User.IsInRole("1"))
    {
        <li>
            <a class="@(ViewContext.RouteData.Values["Action"].ToString() == "CreateUser" ? "active" : "")" id="hMenuOrdini" href="@Url.Action("CreateUser","Account")"><i class="gi gi-user sidebar-nav-icon"></i><span class="sidebar-nav-mini-hide">Lista utenti</span></a>
        </li>
    }
    @*
            <li>
                <a id="hMenuKit" href="@Url.Action("Index","KitHead")"><i class="gi gi-wrench sidebar-nav-icon"></i><span class="sidebar-nav-mini-hide">Kit</span></a>
            </li>
            <li>
            <a id="hMenuClienti" href="@Url.Action("Index","Customer")"><i class="gi gi-link sidebar-nav-icon"></i><span class="sidebar-nav-mini-hide">Clienti</span></a>
        </li>
        <li>
            <a id="hMenuClienti" href="@Url.Action("Index","Articles")"><i class="gi gi-film sidebar-nav-icon"></i><span class="sidebar-nav-mini-hide">Prodotti</span></a>
        </li>*@

</ul>
    <!-- END Sidebar Navigation -->
}
else
{
    <!-- Sidebar Navigation -->
    <ul class="sidebar-nav">
        <li>
            <a href="@Url.Action("Index","Home")" class="active"><i class="gi gi-log_in sidebar-nav-icon"></i><span class="sidebar-nav-mini-hide">Login</span></a>
        </li>

    </ul>
    <!-- END Sidebar Navigation -->
}

OrdiniSDG/Views/Shared/_UserInfoPartial.cshtml
@using Microsoft.AspNet.Identity
@if (Request.IsAuthenticated)
{
    <!-- User Info -->
    <div class="sidebar-section sidebar-user clearfix sidebar-nav-mini-hide">
        @*<div class="sidebar-user-avatar">
            <a href="page_ready_user_profile.html">
                <img src="~/Content/img/placeholders/avatars/avatar2.jpg" alt="avatar">
            </a>
        </div>*@
        <div class="sidebar-user-name">@User.Identity.GetUserName()</div>
        <div class="sidebar-user-links">
            @*<a href="page_ready_user_profile.html" data-toggle="tooltip" data-placement="bottom" title="Profile"><i class="gi gi-user"></i></a>*@
            @*<a href="page_ready_inbox.html" data-toggle="tooltip" data-placement="bottom" title="Messages"><i class="gi gi-envelope"></i></a>*@
            <!-- Opens the user settings modal that can be found at the bottom of each page (page_footer.html in PHP version) -->
            @*<a href="javascript:void(0)" class="enable-tooltip" data-placement="bottom" title="Settings" onclick="$('#modal-user-settings').modal('show');"><i class="gi gi-cogwheel"></i></a>*@

            @using (Html.BeginForm("LogOff", "Account", FormMethod.Post, new { id = "logoutForm", @class = "navbar-left" }))
            {
                @Html.AntiForgeryToken()

                <a href="javascript:document.getElementById('logoutForm').submit()" data-toggle="tooltip" data-placement="bottom" title="Logout"><i class="gi gi-log_out"></i></a>
            }
        </div>
    </div>
    <!-- END User Info -->
}